### PR TITLE
Upgrade PHPStan

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by paveljanda** [comment]
I think it broke the CI. Could you please fix it? Thx.

**Comment by petrparolek** [comment]
could you help me with `Error: Class "Damejidlo\DateTimeFactory\DateTimeImmutableFactory" not found` please?

**Comment by paveljanda** [comment]
This MR is no longer needed, see https://github.com/contributte/jsonrpc/pull/17

**Comment by petrparolek** [comment]
But, there is old version of PHPStan

**Comment by paveljanda** [comment]
But there was an obsolete gamee package. I will fix it. 👍

**Comment by paveljanda** [comment]
@petrparolek Hm, where is old phpstan? jsonrpc supports phpstan 1.3 with no problem

**Pull request closed without merging**
